export const GET_REPORT_REQUEST = 'GET_REPORT_REQUEST';
export const GET_REPORT_SUCCESS = 'GET_REPORT_SUCCESS';
export const GET_REPORT_FAILED = 'GET_REPORT_FAILED';

export const TRACK_ACTION_REQUEST = 'TRACK_ACTION_REQUEST';
export const TRACK_ACTION_SUCCESS = 'TRACK_ACTION_SUCCESS';
export const TRACK_ACTION_FAILED = 'TRACK_ACTION_FAILED';