export const GET_SELECT_DAY_REPORT_REQUEST = 'GET_SELECT_DAY_REPORT_REQUEST';
export const GET_SELECT_DAY_REPORT_SUCCESS = 'GET_SELECT_DAY_REPORT_SUCCESS';
export const GET_SELECT_DAY_REPORT_FAILED = 'GET_SELECT_DAY_REPORT_FAILED';

export const GET_RANGE_DAYS_REPORT_REQUEST = 'GET_RANGE_DAYS_REPORT_REQUEST';
export const GET_RANGE_DAYS_REPORT_SUCCESS = 'GET_RANGE_DAYS_REPORT_SUCCESS';
export const GET_RANGE_DAYS_REPORT_FAILED = 'GET_RANGE_DAYS_REPORT_FAILED';

export const TRACK_ACTION_REQUEST = 'TRACK_ACTION_REQUEST';
export const TRACK_ACTION_SUCCESS = 'TRACK_ACTION_SUCCESS';
export const TRACK_ACTION_FAILED = 'TRACK_ACTION_FAILED';